---
# defaults file for post-install
usernames:
- user11
- user12
- user13
- user14
ntp0: 0.north-america.pool.ntp.org
ntp1: 1.north-america.pool.ntp.org
ntp2: 2.north-america.pool.ntp.org
ntp3: 3.north-america.pool.ntp.org
ntp_path: /etc/ntp.conf
